#!/bin/bash
# Use sql file generated by log2sql
nexttime(){
    sqlite3 $sqlfile <<EOF
select min(time) from stream
 where time > ${time:=0}
 ${site:+ and id == '$site'}
 ${input:+and snd == '$input'}
;
EOF
}
next(){
    time=$(nexttime)
    [ "$time" ] || return 1
}
fields(){
    sqlite3 -line $sqlfile <<EOF | tr -d ' '
select * from stream
 where time == $time; 
EOF
}
setvar(){
    while read line; do
        warn $line
        eval "$line"
    done < <(fields)
}

warn(){
    echo $C1"DEVSIM"$C0":$*" > /dev/stderr
}

server(){
    socat -v udp-listen:8888,reuseaddr,fork exec:"$0 -" & exit
}

[ "$1" ] ||{  echo "Usage:${0##*/} (-d) [site]";exit 1; }
[ "$1" = -d ] && server
[ "$1" = - ] || site=$1
time=0
sqlfile="$HOME/.var/log/stream.sq3"
warn "Init"
while : ; do
    input=$(input64)
    next || next || break
    setvar
    sleep $dur
    echo -n $rcv|base64 -d
done
warn "No find $cmd"
