#!/bin/bash
# Use sql file generated by log2sql
nexttime(){
    sqlite3 $sqlfile <<EOF | grep .
select min(time) from stream
 where time > ${time:=0}
 ${site:+ and id == '$site'}
 ${input:+and snd == '$input'}
;
EOF
}
next(){
    time=$(nexttime) && return
    warn "Rewinded"
    time=$(nexttime) || return 1
}
fields(){
    sqlite3 -line $sqlfile <<EOF | tr -d ' '
select * from stream
 where time == $time; 
EOF
}
setvar(){
    while read line; do
        eval "$line"
    done < <(fields)
}

warn(){
    echo "DEVSIM:$*" > /dev/stderr
}

server(){
    # To keep alive an exec command, it should be first item
    socat exec:"$0 -" udp-recvfrom:8888,reuseaddr,fork & exit
}

[ "$1" ] ||{  echo "Usage:${0##*/} (-d) [site]";exit 1; }
[ "$1" = -d ] && server
[ "$1" = - ] || site=$1
time=0
sqlfile="$HOME/.var/log/stream.sq3"
warn "Init"
while : ; do
    input=$(input64)
    next || break
    setvar
    warn $time
    sleep $dur
    echo -n $rcv|base64 -d
done
warn "No find $cmd"
